version: "3"
services:
  web:
    build: elearn/.
    links:
      - db
    depends_on:
      - db
    environment:
      - DB_USER="user"
      - DB_PASSWORD="password"
      - NODE_ENV="development"
    ports:
      - 3000:3000
      - 9000:9000
  db:
    image: mongo:latest
    container_name: "mongodb"
    restart: always
    volumes:
      - /tmp:/data/db
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGODB_USER="user"
      - MONGODB_PASS="pass"
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet

#volumes:
  #db_data:/tmp
