version: "3"
services:
  web:
    build: portfolio/.
    depends_on:
      - db
    environment:
      DB_USER: user
      DB_PASSWORD: password
  db:
    build: mysql/.
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
